default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: book_club_development

test:
  <<: *default
  database: book_club_test

production:
  <<: *default
  database: book_club_production
  username: book_club
  password: <%= ENV["BOOK_CLUB_DATABASE_PASSWORD"] %>